server:
  port: 8080

spring:
  application:
    name: demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager=true: spring.cloud.sentinel.eager=true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'heapdump' #内存转储存在泄漏风险，关掉内存转储
  endpoint:
    health:
      show-details: always